sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 10.18
  - 12
  - 14
  - 15
before_install:
  - nvm install-latest-npm
install: npm install
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta
    - next

jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
